export const WAD_PROFILES = [
  {
    id: "veka-82-passive",
    name: "Perfect Passive",
    family: "VEKA 82",
    category: "PVC kozijnen",
    depthMm: 82,
    chambers: 7,
    glazing: "32 / 44 / 52 mm",
  },
  {
    id: "veka-76-balance",
    name: "Perfect Balance",
    family: "VEKA 76",
    category: "PVC kozijnen",
    depthMm: 76,
    chambers: 5,
    glazing: "afhankelijk van uitvoering",
  },
  {
    id: "veka-76-balance-pro",
    name: "Perfect Balance Pro",
    family: "VEKA 76",
    category: "PVC kozijnen",
    depthMm: 76,
    chambers: 5,
    glazing: "afhankelijk van uitvoering",
  },
  {
    id: "veka-70-elegance",
    name: "Perfect Elegance",
    family: "VEKA 70",
    category: "PVC kozijnen / deuren",
    depthMm: 70,
    chambers: 5,
    glazing: "afhankelijk van uitvoering",
  },
  {
    id: "whs-72-energy",
    name: "Perfect Energy",
    family: "WHS by VEKA 72",
    category: "PVC kozijnen / deuren",
    depthMm: 72,
    chambers: 5,
    glazing: "afhankelijk van uitvoering",
  },
  {
    id: "whs-60-excellent",
    name: "Perfect Excellent",
    family: "WHS by VEKA 60",
    category: "PVC kozijnen / deuren",
    depthMm: 60,
    chambers: 4,
    glazing: "afhankelijk van uitvoering",
  },
  {
    id: "ecosol-70",
    name: "VEKA ECOSOL 70",
    family: "VEKA ECOSOL",
    category: "PVC schuifsysteem",
    depthMm: 70,
    chambers: 3,
    glazing: "24 mm",
  }
];

export const ELEMENT_TYPES = [
  { id: "fixed", label: "Vast glas" },
  { id: "turn-left", label: "Draairaam links" },
  { id: "turn-right", label: "Draairaam rechts" },
  { id: "tilt", label: "Valraam" },
  { id: "tilt-turn-left", label: "Draai-kiep links" },
  { id: "tilt-turn-right", label: "Draai-kiep rechts" },
  { id: "panel", label: "Paneel" },
  { id: "door-left", label: "Deur linksdraaiend" },
  { id: "door-right", label: "Deur rechtsdraaiend" },
  { id: "sliding-left", label: "Schuif links" },
  { id: "sliding-right", label: "Schuif rechts" }
];
